### ISSUE TITLE
super duper cleanup

### ISSUE THREAD

**Issue by flurinduerst** [flurinduerst/WPSeed#14]
![image](https://cloud.githubusercontent.com/assets/9006167/16308543/aedfea0a-3965-11e6-8cfa-e16bfd925d00.png)
called her to clean lots of stuff like
- unused css
- assets
- functions

**Comment by scherii** [comment]
Mr. Flurin. I clean. You pay me.

**Comment by flurinduerst** [comment]
assets cleaned up in 8868534a359b35ace0343a0395c825bd36f586e0

**Comment by flurinduerst** [comment]
css cleaned up in 8f81a19dd22d227b42b630dd9040ec2e8875ca68

**Comment by flurinduerst** [comment]
finished & closed in b769983f4746e2ba67e6c0ec39d8ad6d3076cbf2 🎉
