### ISSUE TITLE
English (en_US) locale missing for Live Preview > Customizing > Menus

### ISSUE THREAD

**Issue by tinacious** [flurinduerst/WPSeed#18]
The subheadings for the menu customization part of the theme is not in English for the en_US locale, though all of the other strings appear to be translated.

Version 0.13.0

![image](https://cloud.githubusercontent.com/assets/1856992/18406545/49bb85d6-76cc-11e6-9b83-439d7b22b876.png)

**Comment by flurinduerst** [comment]
Thanks for pointing this out. Might update this in a future update. For now, you can change the subheadings in [functions/functions-wpsetup.php on Line 41 and 42](https://github.com/flurinduerst/WPSeed/blob/master/functions/functions-wpsetup.php#L41)

**Comment by flurinduerst** [comment]
fixed in b20b4e87aaad6fa2077f6d1a74be3199dd38f3af :)
