### ISSUE TITLE
Incorrect } syntax error

### ISSUE THREAD

**Issue by lindsaymarkward** [flurinduerst/WPSeed#19]
https://github.com/flurinduerst/WPSeed/blob/6816157e94379e26a321ca986dd671be10993ffe/functions/functions-backend.php#L80

This } appears to be extraneous and causes a syntax error, which causes WPDistillery to fail.

Thanks.

**Comment by flurinduerst** [comment]
Thanks for pointing this out. I fixed it in https://github.com/flurinduerst/WPSeed/commit/2117f2cf911e639cb4a7da583d41fdf12dd724c8#diff-69636799ff2cc25a8427b0070b6dfd97
