### ISSUE TITLE
Error in Theme 

### ISSUE THREAD

**Issue by morgangreenwalt** [flurinduerst/WPSeed#29]
Error: "The site is experiencing technical difficulties. Please check your site admin email inbox for instructions."

Error Details in Email:
=============
An error of type E_PARSE was caused in line 235 of the file /wp-content/themes/okeeffe-theme/functions/functions-dev.php. Error message: syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF)

**Comment by flurinduerst** [comment]
Hi Morgan

Is this issue still pending? If so, I'm happy to help. What version of WPSeed are you using?
