### ISSUE TITLE
Error running gulp

### ISSUE THREAD

**Issue by KevinFuret** [flurinduerst/WPSeed#31]
Hey, 

Got this error when running gulp for the first time just after installed : 

```gulp-notify: [Error running Gulp] node_modules/hamburgers/dist/style.min.css
Error: File to import not found or unreadable: vars.
        on line 20 of node_modules/hamburgers/dist/style.min.css
>> @import 'vars';

   ^
```

Thanks a lot ! 🙏

**Comment by flurinduerst** [comment]
Hi Kevin

the folder `node_modules/hamburgers/dist` should only contain 

```
hamburgers.min.css
hamburgers.css
example.html
```

- Did you move any folders "by hand" ? 
- Did you receive any errors on npm install?
- What version of WPSeed are you using?
